name: Build DS Homebrew

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with Docker
        run: |
          docker run --rm -v "$PWD":/src -w /src devkitpro/devkitarm:20241104 make CFLAGS="-Wno-error=implicit-function-declaration"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dspico-usb-gamepad-nds
          path: |
            *.nds
            *.dsi
            *.ids
